import { useRef, useState } from 'react';
import { Button, Checkbox, Input, InputNumber, Select, Tag } from 'antd';
import { adjustmentName, adjustments, sourceAmounts, sourceErrors, switchCollection } from './source-review-model.mjs';
const names = ['张伟','李娜','王强','陈静','刘洋','赵敏','刘童童','孙琪','周芳','赵悦'];
const phones = ['138****1234','138****5678','138****5678','139****4821','136****7712','137****3390','','135****6808','186****2901','138****9876'];
const initialGuests = names.map((name,i)=>({id:String(i+1),name,phone:phones[i],gender:'unknown',notes:i===6?'联系随行人':'',included:true}));
const money = n => `¥${n.toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const modes = {partner:'客户结算',guest:'全部我方代收',split:'分拆收款'};
const genders = {unknown:'未知',male:'男',female:'女'};
export function SourceOrderPrototype({objectPanel,agentPanel,onRecord,onConfirmed,onSubmitReceivable,receivableSubmitted}) {
 const [done,setDone]=useState(false);
 const [guests,setGuests]=useState(initialGuests);
 const [guestDraft,setGuestDraft]=useState(initialGuests);
 const [editing,setEditing]=useState(null);
 const [values,setValues]=useState({partner:'华东旅行社',adults:8,children:2,adultPrice:6800,childPrice:4200,adjustments:[],discountType:'lump',discount:2000,discountNotes:'',collectionMode:'partner',deposit:null,balance:null,settlementNotes:'',notes:''});
 const [draft,setDraft]=useState(values);
 const modeDrafts=useRef({});
 const amounts=sourceAmounts(values);
 const included=guests.filter(g=>g.included);
 const errors=[...sourceErrors(values),...(included.some(g=>!g.name.trim())?['本次录入名单存在空姓名，请补充或取消该行的本次录入勾选']:[])];
 const update=(key,value)=>setDraft(v=>({...v,[key]:value}));
 const number=(key,label,integer=false)=><label>{label}<InputNumber aria-label={label} min={0} precision={integer?0:undefined} value={draft[key]} onChange={v=>update(key,v)}/></label>;
 const patchAdjustment=(i,patch)=>update('adjustments',draft.adjustments.map((row,j)=>i===j?{...row,...patch}:row));
 const sections=[
  {key:'base',title:'客户与报价',summary:`${values.partner} · ${values.adults} 成人 / ${values.children} 儿童 · 单价 ${money(values.adultPrice??0)} / ${money(values.childPrice??0)}`,fields:<><label>客户<Input value={draft.partner} onChange={e=>update('partner',e.target.value)}/></label>{number('adults','成人人数',true)}{number('children','儿童人数',true)}{number('adultPrice','成人单价')}{number('childPrice','儿童单价')}</>},
  {key:'adjustments',title:'团款调整',summary:values.adjustments.length?values.adjustments.map(a=>`${adjustmentName(a)} ${a.direction==='increase'?'+':'−'}${money(a.amount??0)} ${a.customName||''}`).join('；'):'材料明确无调整',fields:<>{draft.adjustments.map((a,i)=><div className="sourceAdjustment" key={i}><label>调整类别<Select aria-label={`调整类别${i+1}`} value={a.kind} options={adjustments.map(([value,label])=>({value,label}))} onChange={kind=>patchAdjustment(i,{kind,direction:adjustments.find(([k])=>k===kind)[2]||'increase'})}/></label><label>方向<Select value={a.direction} disabled={a.kind!=='other'} options={[{value:'increase',label:'增项'},{value:'decrease',label:'减项'}]} onChange={direction=>patchAdjustment(i,{direction})}/></label><label>金额<InputNumber min={0} value={a.amount} onChange={amount=>patchAdjustment(i,{amount})}/></label><label>调整说明<Input value={a.customName} onChange={e=>patchAdjustment(i,{customName:e.target.value})}/></label><Button onClick={()=>update('adjustments',draft.adjustments.filter((_,j)=>j!==i))}>删除调整项</Button></div>)}<Button onClick={()=>update('adjustments',[...draft.adjustments,{kind:'other',direction:'increase',amount:null,customName:''}])}>添加调整项</Button></>},
  {key:'discount',title:'团款优惠',summary:`${values.discountType==='none'?'无优惠':`整单优惠 ${money(values.discount??0)}`} · ${values.discountNotes||'无优惠备注'}`,fields:<><label>优惠方式<Select value={draft.discountType} options={[{value:'none',label:'无优惠'},{value:'lump',label:'整单优惠'}]} onChange={v=>update('discountType',v)}/></label>{draft.discountType==='lump'&&number('discount','优惠金额')}<label>优惠备注<Input.TextArea value={draft.discountNotes} onChange={e=>update('discountNotes',e.target.value)}/></label></>},
  {key:'collection',title:'收款约定',summary:`${modes[values.collectionMode]}${values.collectionMode==='partner'?'':` · ${values.collectionMode==='split'?'客户已收定金':'我方代收定金'} ${values.deposit==null?'待补充':money(values.deposit)} · 我方代收尾款 ${values.balance==null?'待补充':money(values.balance)}`}`,fields:<><label>收款方式<Select value={draft.collectionMode} options={Object.entries(modes).map(([value,label])=>({value,label}))} onChange={mode=>setDraft(v=>switchCollection(v,mode,modeDrafts.current))}/></label>{draft.collectionMode!=='partner'&&<><p>请核对当前收款方；切换模式不转用其他模式金额，恢复的草稿仍需核对后保存。</p>{number('deposit',draft.collectionMode==='split'?'客户已收定金':'我方代收定金')}{number('balance','我方代收尾款')}</>}<label>结算说明<Input.TextArea value={draft.settlementNotes} onChange={e=>update('settlementNotes',e.target.value)}/></label></>},
  {key:'notes',title:'业务备注',summary:values.notes||'无业务备注',fields:<label>业务备注<Input.TextArea value={draft.notes} onChange={e=>update('notes',e.target.value)}/></label>},
 ];
 const confirm=()=>{if(errors.length||editing||done)return;setDone(true);onConfirmed({...values,...amounts,...(values.collectionMode==='partner'?{deposit:0,balance:0}:{}),visitors:included.map(({included,...row})=>row)});};
 const patchGuest=(id,patch)=>setGuestDraft(rows=>rows.map(row=>row.id===id?{...row,...patch}:row));
 return <main className="prototype"><div className="workspace">{objectPanel}{agentPanel}<section className="reviewPane"><div className="paneHeading">{done?'客源单录入结果':'客源单审核'}</div><div className="reviewContent reviewing"><div className="reviewScroll">
 <section className="reviewSection"><h2>{values.partner} · {done?'已录入':'新增客源单'}</h2><Tag color={done?'success':errors.length?'warning':'blue'}>{done?'已确认':errors.length?`待补充 ${errors.length} 项`:'可确认'}</Tag><p>结算金额 {money(amounts.net)} · {modes[values.collectionMode]}</p>{errors.map((e,i)=><p className="resourceWarning" key={i}>{e}</p>)}<p>电话、性别与备注可不填；年龄和电话类型不作为录入字段。</p></section>
 {sections.map(s=><section className="reviewSection" key={s.key}><div className="sectionTitle"><strong>{s.title}</strong>{!done&&<Button type="link" disabled={!!editing&&editing!==s.key} onClick={()=>{setDraft(values);modeDrafts.current={};setEditing(s.key);}}>编辑</Button>}</div><p>{s.summary}</p>{s.key==='collection'&&<><p>{values.settlementNotes||'无结算说明'}</p><p>{values.collectionMode==='partner'?'客户结算，无代收轧差。':`按约定预计：客户补款 ${money(amounts.topUp)} · 返利 ${money(amounts.rebate)}。`}不代表实际到账。</p></>}{editing===s.key&&<div className="sourceGroupFields">{s.fields}<p>仅修改审核稿，确认录入后才保存到业务记录。</p><div><Button onClick={()=>setEditing(null)}>取消</Button><Button type="primary" onClick={()=>{setValues(draft);setEditing(null);}}>保存本组</Button></div></div>}<small>依据：本次报名材料；直接编辑后的内容以用户修订为准。</small></section>)}
 <section className="reviewSection"><strong>客人名单 · {done?'已录':'本次录入'} {included.length} 位 / 计费 {values.adults+values.children} 位</strong><p>未纳入 {guests.length-included.length} 位，保留在本次协作；不改变计费人数。相同电话可能为家庭共用，不自动合并。</p>{!done&&<Button type="link" disabled={!!editing&&editing!=='guests'} onClick={()=>{setGuestDraft(guests.map(g=>({...g})));setEditing('guests');}}>编辑名单</Button>}{editing==='guests'?<div className="sourceGroupFields">{guestDraft.map((g,i)=><div key={g.id}><Checkbox checked={g.included} onChange={e=>patchGuest(g.id,{included:e.target.checked})}>本次录入第 {i+1} 位</Checkbox><label>姓名<Input value={g.name} onChange={e=>patchGuest(g.id,{name:e.target.value})}/></label><label>联系电话<Input value={g.phone} onChange={e=>patchGuest(g.id,{phone:e.target.value})}/></label><label>性别<Select value={g.gender} options={Object.entries(genders).map(([value,label])=>({value,label}))} onChange={gender=>patchGuest(g.id,{gender})}/></label><label>客人备注<Input value={g.notes} onChange={e=>patchGuest(g.id,{notes:e.target.value})}/></label><Button onClick={()=>setGuestDraft(rows=>rows.filter(row=>row.id!==g.id))}>删除候选</Button></div>)}<Button onClick={()=>setGuestDraft(rows=>[...rows,{id:crypto.randomUUID(),name:'',phone:'',gender:'unknown',notes:'',included:false}])}>添加候选</Button><Button onClick={()=>setEditing(null)}>取消</Button><Button onClick={()=>{setGuests(guestDraft);setEditing(null);}}>保存名单</Button></div>:<details><summary>查看名单与未完成项</summary>{guests.map(g=><p key={g.id}>{g.name||'姓名待补充'} · {g.phone||'未提供电话'} · {genders[g.gender]} · {g.notes||'无备注'} · {g.included?(done?'已录入':'本次录入'):'未纳入，待补充'}</p>)}</details>}</section>
 {done&&<section className="reviewSection"><strong>客源单已创建</strong><p>{receivableSubmitted?'已提交应收':'是否继续提交应收？你也可以先查看客源单，稍后再处理。'}</p><p>同一客源的适用账款逐笔展示、整体确认，不登记实际收付款。</p></section>}
 </div><div className="sourceSettlement"><span>原始团款 {money(amounts.gross)} ＋ 调整净额 {money(amounts.adjustment)} − 优惠 {money(amounts.discount)}</span><strong>结算金额 {money(amounts.net)}</strong></div><div className="reviewFooter">{done?<><Button onClick={onRecord}>查看正式客源单</Button>{!receivableSubmitted&&<Button type="primary" onClick={onSubmitReceivable}>继续提交应收</Button>}</>:<><Button onClick={()=>document.querySelector('.embeddedReview > div:not([hidden]) textarea')?.focus()}>返回会话补充</Button><Button type="primary" disabled={!!editing||!!errors.length} onClick={confirm}>确认录入客源单</Button></>}</div></div></section></div></main>;
}
