packages:
  - 'apps/*'
  - 'packages/*'

onlyBuiltDependencies:
  - esbuild
  - prisma
  - '@prisma/client'
  - '@prisma/engines'

allowBuilds:
  esbuild: true
  prisma: true
  '@prisma/client': true
  '@prisma/engines': true
