// Generated by apps/agent/scripts/generate-ai-create-tool-model-schemas.ts. Do not edit.
export const AI_CREATE_TOOL_MODEL_INPUT_SCHEMAS = {
  "getTaskContext": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {},
    "additionalProperties": false
  },
  "searchRouteTemplates": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "keyword": {
        "description": "空白切词后按 AND 匹配模板名、行程段名和目的地，不搜备注",
        "type": "string",
        "maxLength": 200
      },
      "dayCount": {
        "description": "精确等于常用路线默认天数",
        "type": "integer",
        "minimum": 1,
        "maximum": 999
      }
    },
    "additionalProperties": false
  },
  "submitReviewPackage": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "objectVersion": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      },
      "candidates": {
        "minItems": 1,
        "type": "array",
        "items": {
          "oneOf": [
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "name"
                },
                "proposedValue": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "routeName"
                },
                "proposedValue": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "templateId"
                },
                "proposedValue": {
                  "type": "string",
                  "minLength": 1,
                  "maxLength": 200
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "startDate"
                },
                "proposedValue": {
                  "type": "string",
                  "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "endDate"
                },
                "proposedValue": {
                  "type": "string",
                  "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            },
            {
              "type": "object",
              "properties": {
                "fieldKey": {
                  "type": "string",
                  "const": "expectedGuestCountHint"
                },
                "proposedValue": {
                  "type": "integer",
                  "minimum": 0,
                  "maximum": 9999,
                  "description": "预计人数的数字，例如 12；不要输出“约12人”等文本"
                },
                "clarity": {
                  "type": "string",
                  "enum": [
                    "clear",
                    "needs_confirmation",
                    "undetermined"
                  ]
                },
                "evidence": {
                  "minItems": 1,
                  "type": "array",
                  "items": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "user_message"
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          },
                          "sequence": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "messageId": {
                            "type": "string",
                            "minLength": 1
                          }
                        },
                        "required": [
                          "kind",
                          "excerpt",
                          "sequence"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "system_derivation"
                          },
                          "rule": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 200
                          }
                        },
                        "required": [
                          "kind",
                          "rule"
                        ],
                        "additionalProperties": false
                      },
                      {
                        "type": "object",
                        "properties": {
                          "kind": {
                            "type": "string",
                            "const": "material_region"
                          },
                          "materialId": {
                            "type": "string",
                            "minLength": 1
                          },
                          "parseResultVersion": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "pageNumber": {
                            "type": "integer",
                            "exclusiveMinimum": 0,
                            "maximum": 9007199254740991
                          },
                          "excerpt": {
                            "type": "string",
                            "minLength": 1,
                            "maxLength": 2000
                          }
                        },
                        "required": [
                          "kind",
                          "materialId",
                          "parseResultVersion",
                          "pageNumber",
                          "excerpt"
                        ],
                        "additionalProperties": false
                      }
                    ]
                  }
                }
              },
              "required": [
                "fieldKey",
                "proposedValue",
                "clarity",
                "evidence"
              ],
              "additionalProperties": false
            }
          ]
        },
        "description": "每个字段最多一条候选；多个可能值时只提交最可能的一条"
      }
    },
    "required": [
      "objectVersion",
      "candidates"
    ],
    "additionalProperties": false
  },
  "getMaterialParseResult": {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "materialId": {
        "type": "string",
        "minLength": 1,
        "description": "冻结投影资料索引中的 materialId"
      },
      "parseResultVersion": {
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991,
        "description": "冻结投影资料索引中的 parseResultVersion，必须原样传入"
      },
      "pageNumber": {
        "description": "可选。按页读取原文；truncated 为 true 或 pageCount 较大时必须传入",
        "type": "integer",
        "exclusiveMinimum": 0,
        "maximum": 9007199254740991
      }
    },
    "required": [
      "materialId",
      "parseResultVersion"
    ],
    "additionalProperties": false
  }
} as const
