import { writeFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { standardSchemaToJSONSchema } from '@mastra/core/schema'
import { createGetMaterialParseResultTool } from '../src/get-material-parse-result.tool'
import { createGetTaskContextTool } from '../src/get-task-context.tool'
import { createSearchRouteTemplatesTool } from '../src/search-route-templates.tool'
import { createSubmitReviewPackageTool } from '../src/submit-review-package.tool'

const config = {
  apiBaseUrl: 'http://localhost:3000',
  serviceSecret: 'schema-generation-only',
  modelApiKey: 'schema-generation-only',
}
const tools = {
  getTaskContext: createGetTaskContextTool(config),
  searchRouteTemplates: createSearchRouteTemplatesTool(config),
  proposeReviewPackage: createSubmitReviewPackageTool(config),
  getMaterialParseResult: createGetMaterialParseResultTool(config),
}
const schemas = Object.fromEntries(
  Object.entries(tools).map(([name, tool]) => [
    name,
    standardSchemaToJSONSchema(tool.inputSchema as never, { io: 'input' }),
  ]),
)
const target = resolve(
  import.meta.dirname,
  '../../../packages/ai-contracts/src/runtime/ai-create-tool-model-schemas.generated.ts',
)
writeFileSync(
  target,
  `// Generated by apps/agent/scripts/generate-ai-create-tool-model-schemas.ts. Do not edit.\nexport const AI_CREATE_TOOL_MODEL_INPUT_SCHEMAS = ${JSON.stringify(schemas, null, 2)} as const\n`,
)
